### ISSUE TITLE
Add Author from Search

### ISSUE THREAD

**Issue by DarkSir23** [philborman/LazyLibrarian#12]
Gives a 404:

`Traceback (most recent call last):
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/pbi/lazylibrarian-amd64/share/lazylibrarian/LazyLibrarian/cherrypy/_cpdispatch.py", line 67, in __call__
    raise sys.exc_info()[1]
HTTPError: (404, 'Missing parameters: AuthorName')`

To help with identifying and fixing issues, please include as much information as possible, including:
### Relevant debug log with api keys and any passwords redacted

Please note - usually a single line of log is not sufficient. The lines just before the error occurs can give useful context and greatly assist with debugging.

**Comment by philborman** [comment]
Thanks, should be fixed now. We use AuthorID instead of AuthorName now,
problems with different authors having the same name.

**Comment by DarkSir23** [comment]
I think that's a fantastic idea :)
